### ISSUE TITLE
Simple map of cities with data in OpenSpending

### ISSUE THREAD

**Issue by rufuspollock** [openspending/ideas#1]
- Simple map (preferably OSM-based e.g. using LeafletJS)
- List of cities in [this Google Spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0AqR8dXc6Ji4JdHZZNUpWQ2paY3FfYTdFNXkxZXZDTWc&usp=sharing)
- Deploy with gh-pages in this repo :-) at e.g. apps.openspending.org/maps (once we have apps up and running!)

**Comment by lucychambers** [comment]
Hi Rufus - could this go in main site issues with a tag?

**Comment by rufuspollock** [comment]
You could do but I'd suggest not because ...

You don't want this stuff swamped with OS "core" issues (a tag does not really solve that) and these are not fixes to the main site: this is stuff that can happen entirely independently and part of OS as project rather than OS tech platform.

**Comment by vitorbaptista** [comment]
As the code to solve this issue will go into this repository, I agree with @rgrp that it should be here. But when that's not the case (i.e. for #2), I would rather have it in the main openspending repository. Maybe tag it with "ideas"?

I already feel that OS' issues are too confusing being spread between two repositories (openspending and openspendingjs)...

**Comment by rufuspollock** [comment]
BTW, the code for this should _not_ go in this repository - this is just a repo for holding issues ;-)

You also know my views on openspendingjs as an app repo ;-)

**Comment by vitorbaptista** [comment]
Uh, I got confused by:

```
* Deploy with gh-pages in this repo :-)
```

So, for me, this would make more sense inside openspending's main repository. I understand that you don't want to use Issues as a TODO list, but I would like to keep everything in the same place, using tags to organize :-)

**Comment by rufuspollock** [comment]
But this isn't just technical stuff and I don't think users find tags that intuitive. If I'm a general community user and find loads of technical bugs listed i'm put off. This is supposed to be high level simple ideas for things to do on OpenSpending" as a whole - not just JS fixes :-)

**Comment by vitorbaptista** [comment]
I understand, I just feel it gets a bit disorganized to have issues related
to OpenSpending spread through these repositories. If I'm a community
member and I want to help, I might go to
https://github.com/openspending/openspending/issues and check the issues
tagged volunteer-{simple,advanced,hard}, or check
https://github.com/openspending/openspendingjs/issues?state=open, and now
this repository.

But anyway, let's agree in disagreeing and move on. All in all, we want to
have more people helping with OpenSpending. If creating this repository
helps, I'm all for it :+1: :-)

2013/2/28 Rufus Pollock notifications@github.com

**Comment by mk270** [comment]
Sprawl

**Comment by rufuspollock** [comment]
FIXED. See https://github.com/openspending/maps and http://apps.openspending.org/maps/

/cc @anderspeders @lucychambers @tryggvib
