### ISSUE TITLE
Add datasets to OpenSpending

### ISSUE THREAD

**Issue by anderspeders** [openspending/ideas#11]
- Links and descriptions of datasets ready for upload (in some cases with light cleaning): 
  https://docs.google.com/a/okfn.org/spreadsheet/ccc?key=0AvdkMlz2NopEdElqWTBJS0Q1Q083VlI3YUFLTl9OY0E#gid=0

**Comment by rufuspollock** [comment]
Could you make the spreadsheet editable for me?

**Comment by rufuspollock** [comment]
I've prepped an outline of the [ETL process in this document](https://docs.google.com/a/okfn.org/document/d/1NMmGqiBgsgbnDPIP1mfGgD5ChUpeo97e5QjO-vPWpuc/edit#) and there is also this overview diagram:

<a href="https://docs.google.com/a/okfn.org/drawings/d/1quRc7emv7fPrezqX9YWfqiAfyk_A7KPZ3N8gux2NSh4/edit"><img src="https://docs.google.com/drawings/d/1quRc7emv7fPrezqX9YWfqiAfyk_A7KPZ3N8gux2NSh4/pub?w=963&amp;h=419"></a>

I recommend we focus on getting stuff cleaned to CSVs and into data.openspending.org

**Comment by rufuspollock** [comment]
I'm suggesting we close this in favour of #16 (loadstatus page) or specific items for particular datasets (personally I think better to just use the spreadsheet and loadstatus rather than issues).
