### ISSUE TITLE
Community Directory - community.openspending.org

### ISSUE THREAD

**Issue by rufuspollock** [openspending/ideas#13]
What?

A place for people to register themselves as "OpenSpending-ers (OSers)" with some info about themselves e.g.
- name
- place - try and look up lon / lat and store
- home page (url)
- twitter
- github (if they have one)
- email (private)
- interests
- skills
## Suggested Implementation
- Store to a google form
  - Then copy over some data to a separate spreadsheet to deal with private info (e.g. email)
- Display on a map
- Display on a list (?)
## Context

See an email like this: http://lists.okfn.org/pipermail/openspending/2013-May/001709.html

**Comment by anderspeders** [comment]
Think this should essentially be identical to our Mapping the Money project, for which the contact list is currently at 130 projects/individuals: 
https://docs.google.com/a/okfn.org/spreadsheet/ccc?key=0AvoV_cBqwo28dHNRQlVJWjh5UGhaeDlTZS1tUWZRZ3c&usp=drive_web

The sheet could be easily updated with the fields you suggest.

**Comment by rufuspollock** [comment]
@anderspeders are these people who are community members or just experts / interested. I think there is a distinction. If they are the same then we should _definitely_ reuse!

**Comment by anderspeders** [comment]
@rgrp Contacts are what I'd call the OS community. The list includes projects using OS (such as budgetstories.md) or projects in the wider field of financial transparency. There are indeed a few policy experts in between. However they could also be considered "friends of OS" or "part of the OS community", even if they're not using the OS platform.

**Comment by rufuspollock** [comment]
I was thinking of this more for self-identified community members - not contacts we have. All the contacts would be publicly listed at community.openspending.org and people coudl self-add.

**Comment by anderspeders** [comment]
+1 for self-identified community!

Just to add that I wouldn't consider the Progress sheet a contact list, but think we could use it as a basis for the community list. We could then attach the google form to build the community with new self-identified members.

**Comment by pwalsh** [comment]
Now is https://github.com/openspending/community.openspending.org/issues/30
