### ISSUE TITLE
Event Directory - events.openspending.org

### ISSUE THREAD

**Issue by rufuspollock** [openspending/ideas#14]
Place to list meetups, online calls, spending parties etc
## Location Online

Could also be apps.openspending.org/events
## Implementation

Google Doc + a timeline

**Comment by anderspeders** [comment]
+1

**Comment by anderspeders** [comment]
We've now got a GoogleDoc for events listings:
https://docs.google.com/spreadsheet/ccc?key=0AkitojFFyvjCdFctck83TFNsSVcwa2IxaU8weWhISXc#gid=0

**Comment by rufuspollock** [comment]
FIXED. http://community.openspending.org/events

@anderspeders do we want a timeline / timemap as well as the calendar? If so probably want to trello this ...
