### ISSUE TITLE
Decide if contracts have a place on OS as separate category

### ISSUE THREAD

**Issue by anderspeders** [openspending/ideas#15]
In countries like Serbia, Ukraine and many EU member states governments provide access to procurement data (in EU named "contract award notices"), while transactional spending data remains off-limits. One could therefore argue that procurement/contracting data is currently the closest we get to transactional spending in many countries when the alternative is a simple budget. 

The question is if OpenSpending, should include such procurement data as these are neither budgetary (as they a legal obligations) nor transactional (as the final price may change, if project goes over budget). Thus:
a) Should we include contracts/procurement data (when these have amounts, date, company ID, government ID, etc.)? and if so, 
b) Would we include a separate category next to budget, expenditure etc.?

**Comment by rufuspollock** [comment]
_Strong_ +1 on including contracts.

**Comment by anderspeders** [comment]
I'd then suggest we add an additional category to the upload section called: 
"Contracts"

**Comment by rufuspollock** [comment]
OK, sounds like this should now be an issue on https://github.com/openspending/openspending/issues?state=open

Also feel you should raise this on list saying: "Hey, people already use OpenSpending to record info related to contracts and this seems like a good idea and it would be good to support this properly ..."

**Comment by rufuspollock** [comment]
@anderspeders it would be to get this closed in favour of a specific openspending core ticket :-)

**Comment by anderspeders** [comment]
@rgrp Was raised and now moving forward with add from Cameroon and France.
