### ISSUE TITLE
Get Involved (Join) page with super simple instructions

### ISSUE THREAD

**Issue by rufuspollock** [openspending/ideas#17]
Things to do:
- 1-2-3: load your local cities data
- Take a look at loadstatus and help load a dataset
- Interesting-or-not: (tbd) crowdcrafting app to review spending
- Review the news: keep an eye on BBC/Bloomberg/ your local news for spending related stories and post them on facebook

**Comment by anderspeders** [comment]
Big +1 for getting a good Get Involved page

+1 for Take a look at loadstatus and help upload a dataset
+1 Reveiew the news: keep an eye...

**Comment by rufuspollock** [comment]
DUPLICATE of https://trello.com/c/BtKykOZy/8-big-sort-out-contribution-process-to-os-from-community-data-pov-not-code (which is FIXED).
